services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: deli_baba
      MYSQL_USER: deli
      MYSQL_PASSWORD: 318866175Kk
      MYSQL_ROOT_PASSWORD: 318866175Kk   # ← חובה כדי שהקונטיינר לא יקרוס
    ports:
      - '3307:3306'
    command:
      [
        "--default-authentication-plugin=caching_sha2_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
