version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: deli-baba-mysql
    restart: always
    env_file:
      - ./apps/api/.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    command:
      [
        "--default-authentication-plugin=caching_sha2_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: deli-baba-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
